import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/**
 * Bundles the CodeMirror editor (src/editor.js + all CM6 deps) into ONE
 * self-contained HTML string and writes it to the RN app as a TS module the
 * WebView imports. Run: `npm run build` in this directory.
 *
 * Output is committed so the app builds without this sub-project's node_modules.
 */

const result = await build({
  entryPoints: ['src/index.js'],
  bundle: true,
  format: 'iife',
  minify: true,
  target: ['safari15', 'chrome100'],
  write: false,
});

const js = result.outputFiles[0].text;

// A minimal, offline, self-contained page. viewport locked so the mobile
// keyboard doesn't zoom the editor.
const html =
  '<!doctype html><html><head>' +
  '<meta charset="utf-8">' +
  '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">' +
  // Only the top-level editor fills the screen; nested read-only editors (the
  // /ask answer views) must size to their content, so scope the rule to #root's
  // direct child rather than every .cm-editor.
  '<style>html,body{height:100%;margin:0;background:#1e1e2e}#root{height:100%}#root>.cm-editor{height:100%}</style>' +
  '</head><body><div id="root"></div>' +
  '<script>' + js + '</script>' +
  '</body></html>';

const outPath = '../src/webview/editorHtml.ts';
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  '// AUTO-GENERATED by webview-editor/build.mjs — do not edit by hand.\n' +
    '// Rebuild with: cd webview-editor && npm run build\n' +
    `export const EDITOR_HTML = ${JSON.stringify(html)};\n`,
);

console.log(`Wrote ${outPath} (${(html.length / 1024).toFixed(0)} KB)`);
